#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allmesh

restore0Dir


# runApplication decomposePar
runParallel -s decompose redistributePar -decompose

runParallel renumberMesh -overwrite

runParallel patchSummary

runParallel potentialFoam

runParallel $(getApplication)

runParallel cumulativeDisplacement

# # runApplication reconstructPar
# runParallel -s reconstruct redistributePar -reconstruct

runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

touch case.foam
#------------------------------------------------------------------------------
